export ZSH="/home/$USER/.oh-my-zsh"

ZSH_THEME="mira"


plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias conf='vim ~/.zshrc'

alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gr='git rm'
alias gd='git diff'
alias gl='git log'

alias restart-kde='killall kdeconnectd; kdeconnectd'

alias open='xdg-open'


alias protontricks='flatpak run com.github.Matoking.protontricks'
alias protontricks-launch='flatpak run --command=protontricks-launch com.github.Matoking.protontricks'
