export ZSH="/home/$USER/.oh-my-zsh"

ZSH_THEME="mira"


plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias conf='vim ~/.zshrc'
alias search='apt seatch'
alias backups='sudo timeshift-gtk'
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gr='git rm'
alias gd='git diff'
alias gl='git log'
alias netstat='sudo netstat'
alias mpv='mpv --profile=720p'
alias fs='flatpak search'
alias fii='flatpak install -y'
alias fr='flatpak remove -y'

alias open='xdg-open'



 


# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/deck/.lmstudio/bin"

# Created by `pipx` on 2025-08-31 23:52:34
export PATH="$PATH:/home/deck/.local/bin"
