export ZSH="/home/$USER/.oh-my-zsh"

ZSH_THEME="mira"


plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias yt='yt-dlp'
alias ytmp3='yt-dlp --extract-audio --audio-format mp3'

alias config='vim ~/.zshrc'
alias install='sudo apt install -y'
alias search='apt seatch'
alias backups='sudo timeshift-gtk'
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gr='git rm'
alias gd='git diff'
alias gl='git log'
alias netstat='sudo netstat'
alias music='mpv --no-video'
alias tools='sel=$(ls ~/linux_files/scripts | fzf) && vim ~/linux_files/scripts/$sel'
alias mpv='mpv --profile=720p'
alias fii='flatpak install -y'
alias fr='flatpak remove -y'

alias open='xdg-open'
alias 2up='sudo apt update && apt list --upgradable'

alias todo='vim ~/.todo.txt'


 
