#!/bin/bash


border="==========================================="



# ============================================
# Information about the script

help(){


	script_name="./$(eval basename "$0")"

	echo -e "\nRenames ALL files in the current directory."
	echo -e "$border\n"

	echo -e "$script_name [NEW_FILE_NAME] \n"
	echo -e "[!] A number will be added at the end of the file name \n"
	echo -e "Ex: $script_name my_file \n"
	echo	"Result: my_file_1.txt"

	echo -e "\n$border \n\n"

}
# =============================================



#===============================
# runs if there is no argument and
# runs the help function


new_name=$1

# Checks for the first argument
if [ -z $new_name ]

	then

		clear
		echo -e "\n[!] no argument was given \n"

		help
		exit

fi


# Prints a message if the directory is empty
if [[ -z $(dir) ]]

	then

		echo -e "\n[!] This directory is empty...\n\n"
		exit

fi




#===========================




# removes whitespace from all files in a directory
rename 's/ //g' *


rename() {

	# Renames every file with a new file name
	# While appending a number to the file name

	let count=1

	for file in $(ls $dir); do

	if [ ! -d "$file" ]; then

		mv $file ${new_name%%.*}_$count.${file##*.}
		let count=count+1

	fi

	done

}

rename
