#!/bin/bash

# Python sets up an http server
# in its current directory and
# the script displays my local IP



clear

border='+++++++++++++++++++++++++++++'

echo -e "$border"
echo "Python Server"
echo -e "$border \n"


my_ip="ip a | grep /24 | awk '{print $2}'"


echo -e "IP: "
eval $my_ip | awk '{print $2}'
echo -e "\n\n"



python -m http.server

