#!/bin/bash

# Prompts the user for a comment about the backup
# then creates a snapshot of the system



divider="================"
red="\e[0;91m"
green="\e[0;92m"
reset="\e[0m"

not_root="\n$red [!] Run as root \n"


clear

if [ "$EUID" != 0 ]
	then echo -e "$not_root"
	exit

fi


echo -e "$green $divider Timeshift Backup $divider \n"


# -p gives us a prompt
read -p "$(echo -e '[+] Comment:' $reset)" input

sudo timeshift --create --comment "$input"
