#!/bin/bash

script_name="$(eval basename $0)"

if [ -z $1 ]; then

	clear
	echo -e "\n\n [!] $script_name needs an argument \n"
	echo -e " Ex: $script_name [File_to_compress] [Output_name] \n\n"
	exit

fi


file_name="$1"
output_name="$2"

/usr/bin/gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=$output_name $file_name
