#!/bin/bash

# Python sets up an http server
# in its current directory and
# the script displays my local IP



clear

border='+++++++++++++++++++++++++++++++++++++'

echo -e "$border"
echo -e "\t Python Server"
echo -e "$border \n"

dir="pwd"
command=$($dir)
echo -e "\n## CURRENT DIRECTORY: $command"

echo -e "\n\n[*] IP: $(ip a | grep 192 | awk '{print $2}') \n\n"


python3 -m http.server

