#!/bin/bash

# Python sets up an http server
# in its current directory and
# the script displays my local IP



clear

border='+++++++++++++++++++++++++++++++++++++'

echo -e "$border"
echo -e "\t Python Server"
echo -e "$border \n"


echo -e "[*] IP: $(ip a | grep 168.50 | awk '{print $2}') \n\n"


python3 -m http.server

