#!/bin/bash

border="========================================="
thin_border="------------------------------------------------"


script_name="$(eval basename $0)"

if [ -z $1 ]; then
	clear

	echo -e "\n [!] $script_name needs an option \n"
	echo -e "$thin_border \n
 -a : Creates a backup and update
 -u : Update system
 -b : Creates a backup
 -e : Encrypts file
 -d : Decrypt file \n\n"

	exit

fi

check_root() {

	if [ "$EUID" != 0 ]; then
		echo -e "\n [!] Run as root \n\n"
		exit
	fi

}

backup() {

	echo "$border"
	echo -e "\t Making Backup..."
	echo -e "$border \n\n"

	timeshift --create --comment "Backup from $script_name"
}



update() {

	echo -e "\n\n$border"
	echo -e "\t Updating..."
	echo -e "$border \n\n"

	apt update
	apt upgrade -y
	/bin/check_reboot
}



optstring="d:abue:"

while getopts ${optstring} option; do
	case ${option} in
		a)
			check_root
			clear
			backup
			update
			;;
		b)
			check_root
			clear
			backup
			;;
		u)
			check_root
			clear
			update
			;;
		e)
			gpg -c $2
			;;
		d)
			gpg $2
			;;
		:)
			echo -e "\n [!] Error: -${OPTARG} requires an argument \n\n"
			exit
			;;
		?)
			echo -e "\n [!] Invalid option: - ${OPTARG} \n\n"
			;;

	esac

done
