#!/bin/bash

# Creates a snapshot of the system, then updates

not_root="\n[!] Run as root \n"

clear

if [ "$EUID" != 0 ]
	then echo -e "$not_root"
	exit

fi


border='================================================'


echo -e "$border"
echo -e "\t[+] Creating Backup..."
echo -e "$border \n"

timeshift --create --comment "Backing-up before updating... (from script)"



echo -e "\n\n$border"
echo -e "\t[*] Updating!"
echo -e "$border \n"
apt update && apt upgrade -y

/bin/check_reboot
